import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import PrimarySearchAppBar from '@/components/NavBar'
import Section1 from '@/components/Section-1'
import ActionAreaCard from '@/components/Section-2'
import Galeria from '@/components/Section-3'
import Footer from '@/components/Footer'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>My-App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
       <PrimarySearchAppBar/>
       <Section1/>
        <section className={styles.Card}>
        <ActionAreaCard/>
        <ActionAreaCard/>
        <ActionAreaCard/>
        <ActionAreaCard/>
        <ActionAreaCard/>
        <ActionAreaCard/>
        </section>
        <Galeria/>
        <Footer/>
      </main>
    </>
  )
}
